$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
     nav:true ,
    autoplay:true,
    autoplayhoverpause:true,
    responsiveClass:true,
    dots:false,
    responsive:{
        0:{
            items:3
        },
        50:{
            items:1
        },
        1000:{
            items:3.2
        }
    }
})
